CONTRIBUTING.md, recognize-contributors.md
- Add document about recognizing contributions
- We should now remember to regularly add contributors. Especially after we merge PRs. This doc also has a cheat sheet for it
=> docs: add document about recognizing contributions

.github/ISSUE_TEMPLATE/blog.md
- .add metadata to blog issue template
=> chore: add metadata to blog issue template

FUNDING.yml
- add github sponsors to funding config
=> chore: add github sponsors to funding config

.github/workflows/automerge.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/welcome-first-time-contrib.yml
1. Add automerge.yml
2. Add sentiment-analysis.yml
3. welcome-first-time-contrib.yml
Resolves #9
=> chore: Cleanup GitHub Actions workflows

repository-settings.md
Moved repository settings file from https://github.com/asyncapi/asyncapi/blob/master/documents/repository-settings.md and added additional info file as specified by issue.
See also #7
=> docs: Move repository-settings and add info on additional workflows needed

.github/workflows/global-workflows-support.yml
- add workflow to replicate workflows from this repo to all others
- with this action, doing https://github.com/asyncapi/.github/issues/13 will be as easy as just editing only https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge.yml and this file will be replicated in all the other repositories
- action source code https://github.com/marketplace/actions/global-workflows-support
Resolves #12
=> feat: add workflow to replicate workflows from this repo to all others

.github/workflows/automerge.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/welcome-first-time-contrib.yml
- fix welcome workflow to use fixed v1
- stop automerge action on draft prs
- bump sentimets report when grater than -6 as so far our channel gets overloaded with many notifications like -4 and -6 even though text is pretty fine and not negative at all
should be merged once https://github.com/asyncapi/.github/pull/14 is merged
Fixes #13
=> fix: update global workflows

.github/workflows/automerge.yml, .github/workflows/global-workflows-support.yml, .github/workflows/lint-pr-title.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/stale-issues-prs.yml, .github/workflows/welcome-first-time-contrib.yml
- need to figure out why this is happening https://github.com/asyncapi/.github/runs/1748813673?check_suite_focus=true#step:3:158
=> ci: bump global action to latest to enable more debug info

.github/workflows/automerge-orphans.yml, .github/workflows/automerge.yml, .github/workflows/global-workflows-support.yml, .github/workflows/lint-pr-title.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/stale-issues-prs.yml, .github/workflows/welcome-first-time-contrib.yml
solution for https://github.com/asyncapi/.github/runs/1749545816?check_suite_focus=true#step:3:482
=> ci: update global action to 0.0.5 for better async operations

.github/workflows/automerge-orphans.yml, .github/workflows/automerge.yml, .github/workflows/global-workflows-support.yml, .github/workflows/lint-pr-title.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/stale-issues-prs.yml, .github/workflows/welcome-first-time-contrib.yml
- use global action with retry on github api requests
=> ci: use global action with retry on github api requests

.github/workflows/automerge-orphans.yml, .github/workflows/automerge.yml, .github/workflows/global-workflows-support.yml, .github/workflows/lint-pr-title.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/stale-issues-prs.yml, .github/workflows/welcome-first-time-contrib.yml
- I was finally able to get this error in my test organization (had to create 40 repos 😄 ). Tested my retry there. 7 runs in a row worked well, while before 1 out of 2 was failing
=> ci: use global workflow v7 to solve github graphql issues

.github/workflows/global-workflows-support.yml
- ignore marketing repo in global workflow
=> ci: ignore marketing repo in global workflow

.github/workflows/welcome-first-time-contrib.yml
- extend welcome message with more details about contributions
=> ci: extend welcome message with more details about contributions

.github/workflows/global-workflows-support.yml
- ignore roadmap repo in global workflo
=> chore: ignore roadmap repo in global workflo

.github/workflows/automerge.yml
- increase wait time and timeouts on automerge action
Resolves #33
=> fix: increase wait time and timeouts on automerge action

.github/workflows/automerge.yml, .github/workflows/global-workflows-support.yml
- This change is needed as my last change made the workflow react on `pull_request_target` to fix `autoapprove` step, but it broke `automerge` that in past versions did not support new event 😞
=> ci: bump automerge action to version supporting pull_request_target

repository-settings.md
This PR updates the instructions for installing global workflows, which can now be installed through GH actions.
=> docs: update how to install global workflows

.github/workflows/if-nodejs-pr-testing.yml
fix based on:
- https://stackoverflow.com/questions/15393821/npm-err-cb-never-called
- https://docs.npmjs.com/cli/v7/commands/npm-cache
- https://stackoverflow.com/questions/57850553/github-actions-check-steps-status
=> ci: fix testing PR workflow to fix npm install issue

CHARTER.md
Sets the adoption date.
Required by LF. @tbenzies please have a look. The charter you sent me looks way outdated compared to the agreed one (this one here).
=> fix: add adoption date to the charter

.github/workflows/if-nodejs-pr-testing.yml, .github/workflows/if-nodejs-release.yml
- https://github.com/marketplace/actions/setup-node-js-environment?version=v2.4.1#caching-packages-dependencies
Hope to resolve #80
Signed-off-by: Hollow Man <hollowman@hollowman.ml>
=> ci: update to latest Setup Node.js workflow to use cache

.github/workflows/automerge.yml
hopefully, this PR Resolves #99
=> ci: fix autoapproved label bug

.github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml, .github/workflows/help-command.yml
Quick fix for command bug.
Resolves #110
=> ci: accept commands when comment created only

.github/workflows/add-good-first-issue-labels.yml, .github/workflows/help-command.yml
- quick fix so bot doesn't talk to itself after using `/help` command on issues. 
- see https://github.com/asyncapi/spec-json-schemas/issues/92
=> ci: fix bug of looping messages caused by /help command

.github/ISSUE_TEMPLATE/blog.md
- Adds more info about how to write a blog post
See also https://github.com/asyncapi/website/issues/90
=> docs: add a guide to blog.md

.github/workflows/lint-pr-title.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/welcome-first-time-contrib.yml
=> ci: ignore bots in some workflows

.github/workflows/global-workflows-support.yml
Mainly related to failing updates of global workflows 
https://github.com/asyncapi/.github/runs/5372444127?check_suite_focus=true
=> ci: update global action to 0.8.1 version

.github/workflows/add-good-first-issue-labels.yml, .github/workflows/global-replicator.yml, .github/workflows/if-docker-pr-testing.yml
- Add a workflow to build Docker images on PRs
- Implement CI caching using the Cache backend API
https://github.com/asyncapi/server-api/issues/50
=> ci: add a workflow to build docker images on pull requests

.github/workflows/if-nodejs-release.yml
Refs https://github.com/asyncapi/spec/pull/834
Refs https://github.com/asyncapi/spec-json-schemas/pull/255
=> ci: fix release workflow to support release branches

.github/workflows/lint-pr-title.yml
Added all the suggestions by @derberg 
- a welcome message with the error message 
- comments are correct now
For examples visit following two links
- [pr 1](https://github.com/Krishks369/.github/pull/16)  
- [pr 2](https://github.com/Krishks369/.github/pull/19)
=> feat: add bot commenting in PR title linter workflow

.github/workflows/lint-pr-title.yml
fixed the comment bot to work as needed
=> fix: always trigger comment bot on PR fail

.github/workflows/global-replicator.yml, .github/workflows/notify-tsc-members-mention.yml, .github/workflows/scripts/README.md, .github/workflows/scripts/mailchimp/htmlContent.js, .github/workflows/scripts/mailchimp/index.js, .github/workflows/scripts/mailchimp/package-lock.json, .github/workflows/scripts/mailchimp/package.json, .gitignore
- we know this new functionality works as it was first merged only in community repo -> https://github.com/asyncapi/community/commit/acb42a92e89c64bca9c0d8a92057fd532376e4c8
- this is how email looks like. Link mentioned there in screen shot points [here](https://asyncapi.us12.list-manage.com/track/click?u=3cdae6aed726d2e7490aec739&id=9595ebe4f6&e=35b74043b1)
- you see new concept of globally managed scripts that will also be replicated. It will make it easier for us to make more rich workflows with reusable code. Another use case if for https://github.com/asyncapi/.github/pull/187 (cc @smoya ). Scripts are basically easier than creating custom actions.
Resolves https://github.com/asyncapi/.github/issues/191
See also …
=> ci: add email sending to TSC notify workflow and new scripts concept

.github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml, .github/workflows/automerge-for-humans-remove-ready-to-merge-label-on-edit.yml, .github/workflows/if-go-pr-testing.yml, .github/workflows/issues-prs-notifications.yml, .github/workflows/link-check-cron.yml, .github/workflows/link-check-pr.yml, .github/workflows/lint-pr-title.yml, .github/workflows/notify-tsc-members-mention.yml
- GitHub has started to invalidate the workflows that contain spaces in empty lines in some repos. 
- the error first appeared in the website repo https://github.com/asyncapi/website/actions/runs/3365538818
=> ci: remove spaces from empty lines

profile/README.md
- updated link to slack
- updated link to newsletter
Fixes https://github.com/asyncapi/.github/issues/195
=> docs: update links in profile readme

profile/README.md
Updated the link of linux foundation press release of AsyncAPI
=> fix: linux foundation link

.github/workflows/if-docker-pr-testing.yml, .github/workflows/if-go-pr-testing.yml, .github/workflows/if-nodejs-pr-testing.yml
-Added 8 other PR titles to each `if` statement in testing workflow.
Resolves #200
=> feat: updated workflow with more skippable PRs

.github/workflows/if-docker-pr-testing.yml, .github/workflows/if-go-pr-testing.yml, .github/workflows/if-nodejs-pr-testing.yml, .github/workflows/lint-pr-title.yml, .github/workflows/sentiment-analysis.yml, .github/workflows/welcome-first-time-contrib.yml
- This replace all the occurrence of allcontributor to allcontributors[bot] for fixing the workflow.
Resolves #223
=> ci: replaced the occurrence of allcontributors to allcontributors[bot]

.github/workflows/automerge.yml
I wish we had https://github.com/asyncapi/.github/pull/159 in place already 😅
=> ci: fix automerge workflow

.github/workflows/if-nodejs-release.yml
Convert conventional-changelog-conventionalcommits to devDependency.
Fixes #237
=> ci: change dependency to devDependency

profile/README.md
fixes :- https://github.com/asyncapi/website/issues/1947
=> docs: fix link to meetings page

.github/workflows/bump.yml
- added spec and bindings as comma-separated repos
- removed html-template
Resolves #264
=> ci: make bump workflow to ignore `spec` and `bindings`

.github/ISSUE_TEMPLATE/bug.yml
- changed `required` from `optional` to `false` 
"Fixes #271"
=> fix: changed required from optional to false in bug.yml

.github/workflows/if-nodejs-pr-testing.yml
- https://github.com/puppeteer/puppeteer/issues/12327
- https://github.com/asyncapi/parser-js/issues/1001
=> fix: downgrade macos-latest to macos-13

.github/actions/slackify-markdown/action.yml
=> ci: "fix: global installs do not work as I expected"

.github/workflows/help-command.yml, .github/workflows/transfer-issue.yml
Correcting the bots behavior 
Related to issue [#1514](https://github.com/asyncapi/generator/issues/1514)
=> refactor: bot is not triggered when writing `/help` inside comment in between words

.github/ISSUE_TEMPLATE/docs-bug.yml, .github/ISSUE_TEMPLATE/docs.yml
Add contributor dropdown to docs and docs-bug issue templates
Fixes #349
=> chore: add contributor dropdown to docs and docs-bug issue templates
