asyncapi/.github

- .github/workflows/automerge-orphans.yml
- As a result of this PR, all repos will get a workflow that runs once a day at midnight and reports if there are any PRs from asyncapi-bot or dependabot that are not merged, while they should
This is what message will show up in #github-new-issues-prs channel
Why we need this? @jonaslagoni found this https://github.com/asyncapi/raml-dt-schema-parser/pull/25 and we agreed that next time we should definitely learn about those cases in an automated way. This PR is a proposal from my side on how we can do this
> ci: add monitoring if there are not merged PRs that should be automerged

- .github/workflows/lint-pr-title.yml
- We discussed we need PR title linter before we can think of automating PR merges through `/merge` comment, instead of asking people to click merge button
- My proposal is to use `amannn/action-semantic-pull-request` as it is the only action that also gives an option to validate the uppercase/lowercase of the subject. I contributed there last week a way to provide a custom error message that explains what went wrong with validation in a more human-friendly manner. 
- yes, we never talked about `should it be uppercase` or `should it be lowercase`. I just noticed I do lowercase always but the majority do uppercase. So let us just stick to one
See also https://github.com/asyncapi/asyncapi/issues/423
> ci: add pull request title linter workflow

- .github/workflows/global-workflows-support.yml
- .github/workflows/if-nodejs-pr-testing.yml
- .github/workflows/if-nodejs-release.yml
- .github/workflows/if-nodejs-version-bump.yml
- .github/workflows/version-bump.yml
- these are workflows that will be populated to all repos, even non-nodejs, but will only work if `package.json` is in the root
**version bump**
- the biggest advantage of this one is that PR creation action that we depend on will be updated globally only in this workflow (easier to fix issues like https://github.com/asyncapi/markdown-template/issues/55), and will not be an integral part of individual release workflows
- we will have to maintain 2 scripts in every nodejs project:
- `generate:assets` that will run scripts like the ones about generating docs. toc in readme or types
- `bump:version` that will run scripts to bump version of the package in package.json
**pr testing**
- changing what nodejs version we are testing in all repos will be as simple as updating just …
> ci: add generic version bump and pr testing and relese workflows for nodejs

- .github/workflows/global-workflows-support.yml
A new repository has been created to start documenting what the "AsyncAPI Event Gateway" should look like.
This PR adds https://github.com/asyncapi/event-gateway to the list of ignored repositories as, of now, no code will be added to such repository.
> ci: ignore event-gateway repository

- .github/workflows/if-go-pr-testing.yml
Part of https://github.com/asyncapi/shape-up-process/issues/94
This PR adds a new workflow for **Go** projects. It runs two steps:
- **lint**
- It runs [golangci-lint](https://golangci-lint.run/) linter, which it is a tool that runs the most common linters for go.
- Note: The configuration for the linters are up to each repository (via `.golangci.yml` file), however I think it makes sense if we create a repository template for Go projects that contain, among others, that file. I created a [gist](https://gist.github.com/smoya/35720dd325025dc5665a4f86d1849aae) containing all the config we might want to set.
- **test**
- It ensures the app can be built.
- It runs tests.
Note: The golangci-lint gh action not only fails the build in case of lint issues but it shows those issues in the PR …
> ci: add go-pr-testing workflow

- .github/workflows/automerge.yml
- recently autoapprove workflows were failing and this is the issue https://github.com/hmarr/auto-approve-action/issues/183 that explains what has changed to default GITHUB token
> ci: update autoapprove workflow to v2 and pr target event

- .github/workflows/global-workflows-support.yml
This PR change allows triggering `global-workflows-support` workflow manually from Github UI. 
More info on https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> ci: allow running global-workflows-support workflow manually

- .github/workflows/global-workflows-support.yml
It adds the `training` repo to the list of repos to ignore.
> chore: add training repo to the list of repos to ignore

- .github/workflows/if-nodejs-release.yml
- .github/workflows/if-nodejs-version-bump.yml
- Pin `next` and `**-release` branches to `if-nodejs-release` workflows.
- Update `if-nodejs-version-bump` workflow including `next` branch.
`next` branch at the moment is only used in `react-component` repo.
> ci: pin to nodejs workflows next and releases branches

- .github/workflows/global-workflows-support.yml
Now that the event-gateway repo is gonna have Go code inside, we need to remove it from the ignore list.
> ci: enable event-gateway repo

- .github/workflows/automerge-orphans.yml
- .github/workflows/automerge.yml
- add more logs to orphan alerts workflow to figure out why some are not reported. More info: https://github.com/asyncapi/.github/issues/59
- make sure auto-approve job doesn't approve PR that are already merged and released to not confuse community. Resolves https://github.com/asyncapi/.github/issues/58
- I increased autoapprove delay to 30 sec and we will gain around 3min on that workflow. Did it because of https://github.com/asyncapi/.github/issues/58 and tests that are really long-running there and we need to cover that.
One PR with 2 unrelated changes to have just one update PR in all repos, and not 2, one after another.
> fix: add more logs to orphan alerts workflow and improve auto-approve

- .github/workflows/bump.yml
- merge of this PR cause distribution of this workflow in all repositories and overwrite of the following files in the following repos:
- https://github.com/asyncapi/generator/blob/master/.github/workflows/bump.yml
- https://github.com/asyncapi/generator-hooks/blob/master/.github/workflows/bump.yml
- https://github.com/asyncapi/generator-react-sdk/blob/master/.github/workflows/bump.yml
- https://github.com/asyncapi/modelina/blob/master/.github/workflows/bump.yml
- https://github.com/asyncapi/raml-dt-schema-parser/blob/master/.github/workflows/bump.yml
- https://github.com/asyncapi/openapi-schema-parser/blob/master/.github/workflows/bump.yml
- https://github.com/asyncapi/parser-js/blob/master/.github/workflows/bump.yml
- …
> feat: introduce bump workflow as global

- .github/workflows/automerge-orphans.yml
- .github/workflows/bump.yml
- .github/workflows/issues-prs-notifications.yml
There was a problem the workflow that checks daily for unmerged PRs was not always reporting all the PRs. Some PRs were really waiting for ages to be merged.
Reason was that workflow is not paging-proof and in repos that have over 100PRs it could never work. Now GraphQL query pulls only PRs that have state `OPEN`. So now this action is future-proof and we will have to start to worry if fails only when we will have more than 100 open PRs on a repo. I think once that happens we will have many other bigger issues than this 😆 
Fixes https://github.com/asyncapi/.github/issues/59
Since discussions are out of beta, now GitHub Actions also support it and we should integrate them with our existing workflow that notifies us about every new pr and issue
Had to …
> fix: improve alerts on orphan bot prs and discussions and use latest bump

- .github/workflows/welcome-first-time-contrib.yml
global workflow action doesn't support yet removal of workflows, only when they are created or modified. So need to bring workflow back and disable it, only this way it will be propagated to other repos
> chore: bring welcome workflow back but disabled

- profile/README.md
> chore: fix typo on asyncAPI readme

- profile/README.md
Move static Spec Detail URL to Netlify Router based
- change Spec URL Detail from static version (https://www.asyncapi.com/docs/specifications/v2.2.0) to router based(https://www.asyncapi.com/docs/specifications/latest)
Fixes #82
> docs: change spec details URL

- .github/workflows/stale-issues-prs.yml
unfortunately, I did not notice that new version of the Stale action changed a bit the config property name by adding plural `s` 🤦🏼 
as a result all issues and PRs with `keep-open` were marked by stale action as candidates for closure anyway.
sorry, I will review all the stale bot emails from today and do some cleanup of those at the same time
> ci: update stale workflow to ignore specific labels

- .github/workflows/if-nodejs-release.yml
As in title: set git to use LF in test step in nodejs-release workflow - adding missing first step:
```
- name: Set git to use LF #to once and for all finish neverending fight between Unix and Windows
run: |
git config --global core.autocrlf false
git config --global core.eol lf
```
Failing release process in parser-js - https://github.com/asyncapi/parser-js/runs/4381967909?check_suite_focus=true
> ci: set git to use LF in test step in nodejs-release workflow

- .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
- .github/workflows/automerge-for-humans-remove-ready-to-merge-label-on-edit.yml
the problem with the current workflow that secures merging from "evil" contributors is that it doesn't check if the `ready-to-merge` label is even there, so it basically fails as it tries to remove a label that is not added to PR
> ci: improve removal of ready-to-merge label only when present

- .github/workflows/automerge-for-humans-merging.yml
- .github/workflows/automerge.yml
As @jonaslagoni noticed [here](https://github.com/asyncapi/modelina/pull/547#issuecomment-1004064050) automerge that I recently introduced do not include the number of the PR that was behind the squashed commit. I fix it with this PR and also fix it for automerging for bots too
I tested it [here](https://github.com/derberg/test-experiment/blob/master/.github/workflows/automerge-for-humans.yml) and result was [this](https://github.com/derberg/test-experiment/commit/7196d94002c445d96d9e416c23acfeef800b5ec0)
> ci: include pr number in commit message when automerging

- .github/workflows/if-nodejs-release.yml
Generate docker image in `nodejs-release`:
- add needed envs to push Docker image to DockerHub
If someone want to release docker image have to install `@semantic-release-plus/docker` package in the project and add needed config to the `semantic-release` config. Also need to define Docker Image's build script in the `release` script. Example PR: https://github.com/asyncapi/server-api/pull/24
Part of https://github.com/asyncapi/server-api/pull/24
> ci: generate docker image in nodejs-release

- .github/workflows/help-command.yml
- .github/workflows/if-nodejs-release.yml
This PR adds all the default semantic-release branches to the release workflow for node apps.
See [semantic-release docs](https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches).
This PR will also make Genie behave properly, who has been offering help randomly to people that didn't ask for it 😅 .
Relates to https://github.com/asyncapi/parser-js/pull/442#discussion_r783098429
> fix: include all semantic-release default branches for the release workflow + fix Genie

- .github/ISSUE_TEMPLATE/docs.yml
This PR addresses a mistake I made in the `docs` label for the `docs issue template.` I had originally used a label of `new doc 📄` and also named the `.yml` template as `new doc`. 
This is incorrect since not all Docs issues opened will necessarily be for creating a new piece of documentation. Thus, this PR fixes this assumption by renaming the template and fixing mentions therein of `new docs`.
> docs: fixing incorrect docs label in issue template

- .github/workflows/automerge.yml
- .github/workflows/autoupdate.yml
* Autoupdate branches using AsyncAPI bot instead of Github Actions.
* Check GitHub `event actor` instead of `PR Author` before autoapproving.
Fixes #119
> ci: fix 'automerge' bug + don't run 'autoupdate' for bot branches

- .github/workflows/bump.yml
- .github/workflows/if-go-pr-testing.yml
- .github/workflows/if-nodejs-pr-testing.yml
- skip testing for `allcontributors` and `asyncapi-bot` in certain PR types.
fixes #116
> ci: ignore testing for bots in certain PRs

- .github/workflows/bump.yml
- .github/workflows/notify-tsc-members-mention.yml
This workflow throws a message in a dedicated channel when there is a mention of the GitHub team that groups all technical steering committee members:
- new discussion, issue or PR that mentions the team
- new or edited comment in issue or PR  that mentions the team (message links back to the comment)
- new comment in discussion and new comment/reply to a comment in discussion (message links back to the comment)
- reopened issue or PR that mentions the team
Because of `if` condition in the job, and not steps, workflow is skipped if TSC members are not mentioned
I tested this workflow in new channel `95_bot-tsc-members-mentioned`. Below you can see example messages that were triggered from my [test repo](https://github.com/derberg/test-experiment/actions/runs/1807131912).
See also …
> ci: new workflow to notify TSC members in slack

- .github/workflows/automerge.yml
- .github/workflows/autoupdate.yml
- .github/workflows/bump.yml
- .github/workflows/if-go-pr-testing.yml
- .github/workflows/if-nodejs-pr-testing.yml
- .github/workflows/if-nodejs-release.yml
- .github/workflows/if-nodejs-version-bump.yml
- .github/workflows/issues-prs-notifications.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/notify-tsc-members-mention.yml
- .github/workflows/release-announcements.yml
- .github/workflows/sentiment-analysis.yml
- .github/workflows/stale-issues-prs.yml
- .github/workflows/welcome-first-time-contrib.yml
- CODEOWNERS
GitHub started validating CODEOWNERS and now we know why automated assignment of reviewers to PRs never worked....because our CODEOWNERS files like https://github.com/asyncapi/.github/blob/master/CODEOWNERS were broken.
We are not allowed to add GitHub Actions bot to CODEOWNERS and this is why I created another bot, `asyncapi-bot-eve` that will be responsible for accepting PRs from `asyncapi-bot`.
`asyncapi-bot-eve` is already part of `bots` team where `asyncapi-bot` is. So it is already in all repos added as maintainer with rights to approve.
The only thing that is required after merge of this PR is that every maintainer needs to fix their CODEOWNERS by replacing `@github-actions[bot]` with `@asyncapi-bot-eve`
fixes https://github.com/asyncapi/.github/issues/112
also resolves …
> ci: use custom bot to approve automated PRs

- .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
- .github/workflows/autoupdate.yml
- .github/workflows/help-command.yml
- This PR removes the ability to update the PR branch with `/autoupdate` but it will still keep the PR's branch updated against the **FUTURE** changes to the target branch.
- Resolves the issue where it posts a comment even if the PR branch is up-to-date. https://github.com/asyncapi/website/pull/644#issuecomment-1088867508
- The ability to update the PR with `/autoupdate` will be added in the follow-up commits. Or a follow-up PR if we want to merge it quickly.
> ci: fix autoupdate errors

- .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
- using multiple steps for adding `ready-to-merge` label was problematic and was causing bugs.
as reported here: https://github.com/asyncapi/.github/pull/153#issuecomment-1092765679
- It is now easier to maintain and debug.
> ci: use a single step for adding read-to-merge label

- .github/workflows/link-check-cron.yml
- .github/workflows/link-check-pr.yml
Rename env from  `SLACK_DOCS_URL` to `SLACK_WEBHOOK_URL` in `link-check-cron.yml`
> fix: rename env from  `SLACK_DOCS_URL` to `SLACK_WEBHOOK_URL`

- .github/workflows/link-check-cron.yml
- .github/workflows/link-check-pr.yml
- new git command related to https://stackoverflow.com/questions/71849415/cannot-add-parent-directory-to-safe-directory-on-git
- modified slack notification to share only relevant details for the cron-scheduled validation
> fix: improve markdown links validation

- .github/workflows/automerge-for-humans-add-ready-to-merge-or-do-not-merge-label.yml
- .github/workflows/automerge-orphans.yml
- .github/workflows/link-check-cron.yml
- .github/workflows/link-check-pr.yml
- Don't show the out-of-date message if the branch is not protected.
for example:  https://github.com/asyncapi/spec-json-schemas/pull/199#issuecomment-1097698492, https://github.com/asyncapi/spec/pull/584#issuecomment-1099024685
fixes #158
> ci: improve out-of-date message on PRs + some other minor issues

- SUPPORT.md
- mlc_config.json
this PR is supposed to fix all the [broken links](https://github.com/asyncapi/.github/runs/6143314696?check_suite_focus=true) in markdown files across the repo.
> docs: fix links in Markdown files

- .github/workflows/autoupdate.yml
Autoupdate do not work with forks -> https://github.com/asyncapi/website/runs/6361700980?check_suite_focus=true
Reason is that we use there token of wrong bot, `Eve` is the right one as `Eve` is a codeowner in all projects, so only `Eve` bot have `write` access to forks as a valid maintainer.
At least I think this is the solution 😆
> ci: change token for autoupdate to use codeowner token

- .github/workflows/global-replicator.yml
- CODE_OF_CONDUCT.md
Signed-off-by: amino19 <anshumaankrprasad76@gmail.com>
To replicate the `CODE_OF_CONDUCT.md` (COC.md) file to all repositories in the AsyncAPI organization, @derberg suggested me to do a "simple editorial change" in the [COC.md](https://github.com/asyncapi/.github/blob/master/CODE_OF_CONDUCT.md) file; my changes are as follows:
- bullets point `star` to `hyphen` in COC.md
- Restructure GitHub Action for [global-replicator.yml](https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml)
- removed [line 34](https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml#L34) and bring it between L30 & L31. 
Resolves #167
> ci: replicate COC.md to all repositories

- .github/workflows/if-nodejs-release.yml
- .github/workflows/if-nodejs-version-bump.yml
- .github/workflows/link-check-cron.yml
related to https://github.com/asyncapi/dotnet-nats-template/actions/runs/2536516647 and we learned that for at least a month the version bump workflow doesn't work
this PR:
- make sure bump version works the same way release and pr testing workflows
- add slack notifications in case of these workflows fail
> ci: fix version bump workflow and make sure in future we get notified

- .github/workflows/global-replicator.yml
this PR makes us use global workflow `v1` so it is easier to apply patches from the action. Latest patch is with the fix to make `workflow_dispatch` trigger work as expected, as not it was always reporting that no files need replication, even though it is not true.
> ci: use latest global workflow to fix manual run

- .github/workflows/stale-issues-prs.yml
This PR forces the `stale-issues-prs` workflow to close staled issues with the `not planned` reason instead of `completed`, as per completed means a fix, feature, or any other work has been done in order to close it, which in our community, it doesn't happen; we manually close issues that has been fixed/resolved, and stale issues are normally things we won't do.  
Example of issue that has been marked as `completed` but shouldn't: https://github.com/asyncapi/spec/issues/596
> ci: close staled issues with `not planned` reason

- .github/workflows/automerge-for-humans-merging.yml
Something I realized we might need to think about is the fact merging release branches (i.e. `next-major`  or `next-spec`) with squash merging strategy ends up obviously with only one commit being merged, being the author of it the person who created the PR. 
This leads to:
- Losing history of changes introduced. It might not be a real issue (if it hasn’t yet) since we write version notes. However, it’s hard to see where exactly a feature or bug was introduced.
- Losing authority of commits. All changes to such version will appear to be introduced by the person who created the PR.
For the record, the merge is performed automatically by @asyncapi-bot  thanks to the `automerge-for-humans-merging.yml` Github workflow.
This PR fixes the issue with authority, by adding …
> ci: support co-authoring for auto-merged PRs

- .github/workflows/automerge-for-humans-merging.yml
This PR fixes an invalid pipe in the command used to retrieve a list of authors of a PR. See the following example of a broken build: https://github.com/asyncapi/glee/actions/runs/3082079538/jobs/4981350760#logs
cc @Souvikns @derberg @magicmatatjahu
> fix: invalid pipe on list of authors cmd

- .github/workflows/link-check-cron.yml
- .github/workflows/link-check-pr.yml
- .github/workflows/stale-issues-prs.yml
- stale bot was staling issues and next day automatically unstaling - this is fixed with latest version
- link checker was in general behaving weird and throwing lots of false-positives
as you can see, I also started using commits as version pointers. We have global replicator, so we have luxury to use commits, instead invented GH Actions versioning, that is super insecure. I'm happy to explain more if needed
> ci: fix link checker and stale bot

- .github/workflows/lint-pr-title.yml
Updated the job to run only if the error message is not null. So that Blank Comment doesn't happen
> ci: fix bot comment shows up only when PR title is wrong

- .github/pull_request_template.md
- .github/workflows/add-good-first-issue-labels.yml
- Added `break` statement to facilitate `/gfi`
- Correct a minor spelling error in `otherwise` in the PR template
Resolves #169
> fix: add break statement and correct spelling error

- .github/workflows/notify-tsc-members-mention.yml
- .github/workflows/scripts/mailchimp/htmlContent.js
- .github/workflows/scripts/mailchimp/index.js
- title of issue/pr/discussion will now be included in body of email and the email title
- action will not react on edits as already because of it, few times we sent duplicated emails to people. We need to avoid to much spam
Resolves https://github.com/asyncapi/.github/issues/194
> fix: improve email notifications for tsc voting

- .github/workflows/if-nodejs-release.yml
- this change will significantly improve GitHub Actions workload as at the moment release workflow is triggered on every single commit, and tests have to go through until `semantic-release` finds out release is not needed
- I use `startsWith(fromJson` and not `contains(fromJson` like in other workflows because commit message can be multiline, and we do not have 100% assurance that PR was not manually merged and feat/fix was not mentioned somewhere in the message
- I checked if `startsWith` also works with `contains` as there is not direct info in docs, at least I did not find it. I just searched github and found https://github.com/insignias/React/blob/main/.github/workflows/merge-release-pr-to-main.yml#L40
Resolves …
> ci: improve release workflows to skip early

- .github/workflows/scripts/mailchimp/index.js
This PR is fixing a bug that was sending the TSC notification email to all the people in our Mailchimp list, instead of just the ones subscribed to this kind of notification.
> fix: emails not being sent to proper recipients

- .github/workflows/global-replicator.yml
updating name of PHP template as it is not ignored for now and recently bot override the contributors guide that is custom in `php-template`
@KhudaDad414 easy approval 😉
> chore: update new name of php template in generic workflow

- .github/workflows/if-docker-pr-testing.yml
- .github/workflows/if-go-pr-testing.yml
- .github/workflows/if-nodejs-pr-testing.yml
- sometimes `asyncapi-bot-eve` autoupdates a PR and is last actor, so we need to also ignore it in some workflows
- use new pr title for global workflows
> ci: skip workflows with new title and support skip for asyncapi-bot-eve

- profile/README.md
Fix for slack channel name for *contributors*.
> docs: fix contributions slack channel name in main org readme

- .github/actions/slackify-markdown/action.yml
- reverting changes from https://github.com/asyncapi/.github/pull/235/files?diff=split&w=0
- reading markdown input by passing it to environment variable first
Tested:
- slack action example https://github.com/derberg/test-experiment/blob/master/.github/actions/slackify-markdown/action.yml
- workflow example https://github.com/derberg/test-experiment/blob/master/.github/workflows/testtest.yml
- comment in issue example https://github.com/derberg/test-experiment/issues/150#issuecomment-1540116446
- run green example https://github.com/derberg/test-experiment/actions/runs/4926234621/jobs/8801502707
cc @akshatnema 
fixes https://github.com/asyncapi/.github/issues/231
> ci: fix slackify of markdown code

- .github/workflows/help-command.yml
during the migration of the command from using custom action, to using own js script, I forgot to make sure that markdown-related back-ticks should be escaped in code, otherwise JS fails with compilation
@KhudaDad414 once you approve please also just merge
> ci: fix help command related to unexpected `{`

- .github/workflows/global-replicator.yml
- .github/workflows/update-docs-on-docs-commit.yml
- .github/workflows/update-docs-on-docs-commits.yml
- The given PR adds a new workflow responsible for generating docs and creating PR with them when there is a commit with docs: prefix.
Fixes #242
> ci: add update-docs workflow

- README.md
- Update README to add documentation for auto-update docs action workflow.
Related to https://github.com/asyncapi/.github/pull/258
> docs: update readme for update-docs workflow

- .github/workflows/automerge.yml
Sometimes you want to block merging of automated PR, not only of human PR
I wanted to do this in https://github.com/asyncapi/website/pull/2320 with `do-not-merge` label - but bot ignored me
> ci: enable block bot automerge with `do-not-merge`

- .github/workflows/bump.yml
- .github/workflows/global-remover.yml
- .github/workflows/global-replicator.yml
Adds [saunter](https://github.com/asyncapi/saunter) to `repos_to_ignore` to prevent replication of workflow and bumping of packages.
Requested by @derberg in https://github.com/asyncapi/.github/pull/274#pullrequestreview-1928526340
> chore: add saunter to ignored repos list

- .github/workflows/if-go-pr-testing.yml
- .github/workflows/if-nodejs-pr-testing.yml
- .github/workflows/if-nodejs-release.yml
- .github/workflows/if-nodejs-version-bump.yml
- `shell: bash`  resolves https://github.com/asyncapi/.github/issues/278
- I also removed the `npm install` with verbose as it was slowing down CI and with no benefits really. Now we do proper `npm ci`
- one more fix for windows cache (check inline comment
> ci: fix windows issues in few workflows

- .github/workflows/if-nodejs-pr-testing.yml
- .github/workflows/if-nodejs-release.yml
After the fix from yesterday I noticed that the reinstallation that we had in PR testing actually never worked as we used wrong keywords
we should use `outcome` as describe in https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
> ci: fix reinstallation of failure in release and pr testing

- .github/workflows/help-command.yml
Fixed a typo in [help-command.yml#L34](https://github.com/asyncapi/.github/blob/master/.github/workflows/help-command.yml#L34)
Resolves #282
> ci: fix the escape character typo in `/ptal` command

- .github/workflows/please-take-a-look-command.yml
Added a filter to check if reviewer is bot or not so that it is not mentioned in the comment
Resolves #283
> ci: add a filter to check if reviewer is bot or not in `/ptal` command

- .github/workflows/bump.yml
Have you ever seen below
- I'm just personally tired cleaning up CI on daily basis - that is too much
- This is a terrible waste of resources, like big time
This PR uses my latest action that basically reuses existing PRs, but only if they have a custom id marker in it (basically hidden comment in PR description)
Here you see an example that was once created by bump workflow, and then again it was updated with never version of the dependency, without creating new PR -> https://github.com/lukasz-lab/nie-niet-none/pull/48
> ci: use latest bumping action feature to reuse PRs

- .github/workflows/.releaserc
- .github/workflows/if-nodejs-release.yml
In Modelina we have been using `next` since the beginning, however, we decided to remove it from the official workflow 🤨 We did a patch at some point in Modelina, and then I forgot about it.
This PR adds it officially.
> ci: add support for `next` release branch

- .github/workflows/bounty-program-commands.yml
This PR:
- Adds a command that allows to remove the label `bounty` from Bounty Issues, thereby making them usual GitHub issues. The command is invoked when posting a comment in the Bounty Issue that starts with the sequence of characters `/unbounty`.
- Fixes incorrect `RegExp` that matched the sequence of characters `/bounty` placed anywhere in the body of a comment, which led to the invocation of GitHub Actions on casual mention of `@asyncapi/bounty_team`, sometimes in an infinite loop. Now the command `/bounty` is recognized only when it's placed at the beginning of the comment.
> ci: add Bounty Program command `/unbounty`

- .github/workflows/global-replicator.yml
website will have dedicated contrib guide: https://github.com/asyncapi/website/pull/2959
> chore: ignore website for contribution guide replication

- .github/workflows/global-replicator.yml
- .github/workflows/update-maintainers-trigger.yaml
- This PR provides a generic workflow that triggers the "MAINTAINERS.yaml" file update in `community` repository
The main logic is defined in the `community` repo, see: https://github.com/asyncapi/community/pull/1315
Blocked by: https://github.com/asyncapi/community/pull/1314 and https://github.com/asyncapi/github-action-for-cli/pull/397
Fix: https://github.com/asyncapi/community/issues/1269
> ci: trigger MAINTAINERS.yaml update for each CODEOWNERS file change

- .github/workflows/global-replicator.yml
- Added the `destination` property to the `replicate_prettierignore_file` step in the `.github/workflows/global-replicator.yml` workflow.
- This ensures that the `.prettierignore` file is replicated correctly in the repository's root directory (`./`).
- Fixes #316
> fix: add destination for .prettierignore replication

- profile/README.md
Fixed broken link to the latest specification in the organization profile:
Before | After 
-------|------
> docs: fix link to specification reference docs

- .github/actions/slackify-markdown/action.yml
Some repos like studio and glee are using pnpm. Pnpm uses a syntax in the package.json file that npm doesn't recognize as valid, namely `"package-name": "workspace:*"`. The Slackify action in this repo tries to install a dependency on the repo using npm and that causes an error: https://github.com/asyncapi/glee/actions/runs/11571817568/job/32210507703.
To avoid this problem, I'd advocate for simply installing the dependency globally instead.
> ci: install slackify globally to avoid conflicts with pnpm

- .github/actions/slackify-markdown/action.yml
Fixes a problem introduced in #318. Global installs are not available when running "require()" in a script.
As a workaround, I'm creating a new directory with its own package.json file just to run this action. This way, npm won't complain. I checked locally and it worked.
> fix: global installs do not work as I expected

- .github/ISSUE_TEMPLATE/bug.yml
Change the browser with device information in bug issue_template.
Fixes: #328
> chore: replace browser with device information in bug template
